### ISSUE TITLE
Check for correct connectivity in bblocks, before pre-caching splices

### ISSUE THREAD

**Issue by ajasja** [willsheffler/worms#7]
* worms version:  Rosetta version: 2017.48.post.dev+119.fordas.devbase.cce4ea9c848 cce4ea9c848fb89054e27458cfec117fb00bd601 git@github.com:RosettaCommons/main.git 2018-04-16T01:42:35
* Python version:  /home/sheffler/.conda/envs/worms/bin/python

### What I Did
In the flag file I had either

```
--bbconn
    _C ajasjaA
    NC Het:NC
    NN Het:NC
    NN Het:NN
    C_ ajasjaB
```

or  (don't remember exactly)

```
--bbconn
    _C ajasjaA
    NC Het:NN
    NC Het:NN
    NN Het:NN
    C_ ajasjaB
```

And worms precalculated the splices up tp the incorrect connection before throwing an error.

```
Traceback (most recent call last):
  File "/home/sheffler/.conda/envs/worms/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/sheffler/.conda/envs/worms/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sheffler/src/worms_beta/worms/__main__.py", line 5, in <module>
    worms_main(sys.argv[1:])
  File "/home/sheffler/src/worms_beta/worms/app.py", line 203, in worms_main
    raise e
  File "/home/sheffler/src/worms_beta/worms/app.py", line 199, in worms_main
    worms_main2(criteria_list, kw)
  File "/home/sheffler/src/worms_beta/worms/app.py", line 264, in worms_main2
    criteria, merge_bblock=0, print_edge_summary=True, **kw
  File "/home/sheffler/src/worms_beta/worms/ssdag.py", line 290, in simple_search_dag
    **kw
  File "/home/sheffler/src/worms_beta/worms/edge.py", line 24, in Edge
    u, ublks, v, vblks, verbosity=verbosity, **kw
  File "/home/sheffler/src/worms_beta/worms/edge.py", line 88, in get_allowed_splices
    assert (u.dirn[1] + v.dirn[0]) == 1, 'get_allowed_splices dirn mismatch'
AssertionError: get_allowed_splices dirn mismatch
```

**Comment by willsheffler** [comment]
fixed in branch "bridge", will be merged into master soonish. /home/sheffler/src/worms_beta on the digs has the fix.

**Comment by ajasja** [comment]
I'm not sure this is fixed yet.
After ~5 hrs of precalculating splices I got

```
precache splices: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████▉| 63617/63696 [4:42:23<00:21,  3.75it/s]precache splices: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████▉| 63676/63696 [4:42:36<00:05,  3.76it/s]precache splices: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 63696/63696 [4:42:39<00:00,  3.76it/s]

Traceback (most recent call last):
  File "/home/sheffler/.conda/envs/worms/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/sheffler/.conda/envs/worms/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sheffler/src/worms_beta/worms/__main__.py", line 5, in <module>
    worms_main(sys.argv[1:])
  File "/home/sheffler/src/worms_beta/worms/app.py", line 45, in worms_main
    raise e
  File "/home/sheffler/src/worms_beta/worms/app.py", line 41, in worms_main
    worms_main2(criteria_list, kw)
  File "/home/sheffler/src/worms_beta/worms/app.py", line 101, in worms_main2
    criteria, merge_bblock=0, print_edge_summary=True, **kw
  File "/home/sheffler/src/worms_beta/worms/ssdag.py", line 266, in simple_search_dag
    verts_new = [f.result() for f in futures]
  File "/home/sheffler/src/worms_beta/worms/ssdag.py", line 266, in <listcomp>
    verts_new = [f.result() for f in futures]
  File "/home/sheffler/.conda/envs/worms/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/home/sheffler/.conda/envs/worms/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/sheffler/.conda/envs/worms/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/sheffler/src/worms_beta/worms/vertex.py", line 230, in Vertex
    raise ValueError('no way to make vertex: \'' + dirn + '\'')
ValueError: no way to make vertex: 'NN'
```

**Comment by ajasja** [comment]
Here is the relevant conf file 
```
--bbconn
    _C N1_C2_2-E01_DR64_cryo.RK-05_2_RK-05_2_1na0_AB_A_0001_0002_RK-05_2_DHR49_BA_B_0001_0004.c_term.A_0001_0001.OUTER.SID_10
    NC Het NN Het CN Het
    C_ N1_C2_2-E01_DR64_cryo.RK-05_2_RK-05_2_1na0_AB_A_0001_0002_RK-05_2_DHR49_BA_B_0001_0004.c_term.A_0001_0001.OUTER.SID_18
--geometry Bridge()
```
