### ISSUE TITLE
File name too long

### ISSUE THREAD

**Issue by ajasja** [willsheffler/worms#8]
worms beta on digs

### Description

Running some bridge protocols
[NDX0JB~U.ZIP](https://github.com/willsheffler/worms/files/2729136/NDX0JB.U.ZIP)

```
Traceback (most recent call last):
  File "/home/sheffler/.conda/envs/worms/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/sheffler/.conda/envs/worms/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sheffler/src/worms_beta/worms/__main__.py", line 5, in <module>
    worms_main(sys.argv[1:])
  File "/home/sheffler/src/worms_beta/worms/app.py", line 45, in worms_main
    raise e
  File "/home/sheffler/src/worms_beta/worms/app.py", line 41, in worms_main
    worms_main2(criteria_list, kw)
  File "/home/sheffler/src/worms_beta/worms/app.py", line 120, in worms_main2
    kw['context_structure'] = ClashGrid(kw['context_structure'], **kw)
  File "/home/sheffler/src/worms_beta/worms/clashgrid.py", line 17, in __init__
    bbdb.savepose(pdbfile)
  File "/home/sheffler/src/worms_beta/worms/database.py", line 474, in savepose
    with open(fname, 'wb') as out:
OSError: [Errno 36] File name too long: '/home/ajasja/.worms/cache/poses/__home__ajasja__projects__Worms__fibre_staples__04_call_worms_bridge__out__N1_C2_2-E01_DR64_cryo.RK-05_2_RK-05_2_1na0_AB_A_0001_0002_RK-05_2_DHR49_BA_B_0001_0004.c_term.A_0001_0001__N1_C2_2-E01_DR64_cryo.RK-05_2_RK-05_2_1na0_AB_A_0001_0002_RK-05_2_DHR49_BA_B_0001_0004.c_term.A_0001_0001.CORE.pdb.gz.pickle'
```

**Comment by ajasja** [comment]
A new flag was added `--output_short_fnames 1 ` to get around this issue.
