### ISSUE TITLE
File name too long II

### ISSUE THREAD

**Issue by ajasja** [willsheffler/worms#9]
File name too long when saving PDBs:

```
<class 'OSError'>
Traceback (most recent call last):
  File "/home/sheffler/src/worms_beta/worms/app.py", line 202, in worms_main_protocol
    log += filter_and_output_results(criteria, ssdag, result3, **kw)
  File "/home/sheffler/src/worms_beta/worms/output.py", line 260, in filter_and_output_results
    with open(fname + '_asym.pdb', 'a') as out:
OSError: [Errno 36] File name too long: '/home/ajasja/projects/Worms/fibre_staples/04_call_worms_bridge/out/03/SID_10_18.3NNCCNN_mbb0028__0000_105-396-828-1137_N1_C2_2-E01_DR64_cryo.RK-05_2_RK-05_2_1na0_AB_A_0001_0002_RK-05_2_DHR49_BA_B_0001_0004.c_term.A_0001_0001.OUTER.SID_10_ex105_en460_HFuse_ZCON-131_2_2c_2a_1053_ex102_en498_HFuse_ZCON-13_2_2c_2a_1037_ex_ABAA_asym.pdb'

[Errno 36] File name too long: '/home/ajasja/projects/Worms/fibre_staples/04_call_worms_bridge/out/03/SID_10_18.3NNCCNN_mbb0028__0000_105-396-828-1137_N1_C2_2-E01_DR64_cryo.RK-05_2_RK-05_2_1na0_AB_A_0001_0002_RK-05_2_DHR49_BA_B_0001_0004.c_term.A_0001_0001.OUTER.SID_10_ex105_en460_HFuse_ZCON-131_2_2c_2a_1053_ex102_en498_HFuse_ZCON-13_2_2c_2a_1037_ex_ABAA_asym.pdb'
```

**Comment by ajasja** [comment]
A new flag was added `--output_short_fnames 1 ` to get around this issue.
